### ISSUE TITLE
可以合并一下我收集的IP

### ISSUE THREAD

**Issue by ohyeah521** [Aabyss-Team/Ban-Hacker-IP-Plan#1]
我这里也收集了一批恶意IP：[https://github.com/ohyeah521/synology_deny-ip-list](https://github.com/ohyeah521/synology_deny-ip-list)

**Comment by AabyssZG** [comment]
好的，感谢师傅对本项目的支持和反馈🥰

**Comment by AabyssZG** [comment]
在你的项目中抽查了一下，还是有一部分境外IP，诸如：`45.221.75.2` 和 `27.72.46.26`

**Comment by ohyeah521** [comment]
确实有几个，应该不多

**Comment by ohyeah521** [comment]
可以搞个蜜罐，部署一个在线的群晖，把邮件服务，ssh，web服务都打开就可以自动收集最新的恶意IP了

**Comment by AabyssZG** [comment]
我花了一些时间，写了一个筛选IP归属的脚本：https://github.com/AabyssZG/IP-Where
你的项目里面共有 `5966` 行IP，通过筛选得到境内IP `4771` 行，有 `1195` 行境外IP，占比达20%。。。

**Comment by AabyssZG** [comment]
已经将[synology_deny-ip-list](https://github.com/ohyeah521/synology_deny-ip-list)这个开源项目中的IP，进行去重并去除境外的IP，融合到本项目，再次感谢师傅对本项目的支持和反馈
