### ISSUE TITLE
是否考虑共享/收集境外恶意IP地址？

### ISSUE THREAD

**Issue by id7368** [Aabyss-Team/Ban-Hacker-IP-Plan#3]

**Comment by AabyssZG** [comment]
目前是不考虑的，境外网络空间环境复杂，傀儡机、僵尸网络、匿名代理等将会是海量级别的，这不是可控的内容
所以在本项目的防护总体思路中，我写到先是Ban掉所有境外访问，将业务聚焦到国内战场进行防护
